sudo: required
services:
    - docker

before_install:
    - docker build -tjanlikar/docker-app-test -f Dockerfile.dev .

script:
    - docker run -e CI=true janlikar/docker-app-test npm run test -- --coverage
