sudo: required
services:
    - docker

before_install:
    - docker build -tjanlikar/docker-app-test -f Dockerfile.dev .

script:
    - docker run -e CI=true janlikar/docker-app-test npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-app-test"
    env: "DockerAppTest-env"
    bucket_name: "elasticbeanstalk-eu-west-1-106608757305"
    bucket_path: "docker-app-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
